### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by MagicAndre1981** [dud5/editProjFiles#4]
Can you please add Visual Studio 2015 support?

**Comment by dud5** [comment]
I will push an update this week with VS2015 support.

**Comment by MagicAndre1981** [comment]
nice to hear this :+1:

**Comment by dud5** [comment]
The extension already supported VS2015 (if you searched for it within VS2015, it will allow to install).

I also pushed an update that triggered the display of VS2015 under the supported versions in the gallery.

**Comment by MagicAndre1981** [comment]
thanks I was now able to install the new version :)
