### ISSUE TITLE
After closing a project file it still saves by doing Save All

### ISSUE THREAD

**Issue by xperiandri** [dud5/editProjFiles#5]
If I open project file using Edit Proj and then close its document tab it still is kept in memory.
And if I press Ctrl+Shift+S to do Save All a dialog that prompts to reload project appears.
Only restarting Visual Studio solves problem.
Tested in Visual Studio 2015.

**Comment by nholling** [comment]
I've got the exact same problem. Also happens in VS 2013.

**Comment by SamB** [comment]
+1

**Comment by xperiandri** [comment]
Will you update extension with this fix?

**Comment by edumunoz** [comment]
Yes, thanks for reminding me.

As soon as I have access to a Windows machine I'll update the extension in
the gallery.
